### ISSUE TITLE
Broken pipe when sourcing shell widget

### ISSUE THREAD

**Issue by summy00** [denisidoro/navi#366]
sorry, i am not familiar with mac os terminal, thanks.
I want not in navi gui, but in terminal triggle hint directly.

navi 2.7.0

**Comment by summy00** [comment]
I don't know change 'bug' to 'feature', sorry

**Comment by denisidoro** [comment]
Do you mean [this](https://github.com/denisidoro/navi#shell-widget)?

**Comment by summy00** [comment]
it shows:
```
source <(navi widget bash)
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:805:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
any suggestion?

**Comment by denisidoro** [comment]
Are you sure you're using bash? Try running `echo $SHELL`

**Comment by summy00** [comment]
```
echo $SHELL
/bin/bash
```

**Comment by hernanmd** [comment]
I could reproduce the same problem here:

```bash
$ bash --version
GNU bash, versión 5.0.17(1)-release (x86_64-apple-darwin17.7.0)
```

Exporting the backtrace environment variable:

```bash
$ export RUST_BACKTRACE=1
$ source <(navi widget bash)
$ thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:805:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: std::io::stdio::_print
   9: navi::handler::handle_config
  10: navi::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

And the full backtrace:

```bash
$ export RUST_BACKTRACE=full
$ source <(navi widget bash)
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', src/libstd/io/stdio.rs:805:9
stack backtrace:
   0:        0x100e8debc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1216a26f3ce3c114
   1:        0x100ea788e - core::fmt::write::ha0ec7ad9e1aa7104
   2:        0x100e8dc49 - std::io::Write::write_fmt::he79f4e513ba146b5
   3:        0x100e84fea - std::panicking::default_hook::{{closure}}::hdf6a192f990c9642
   4:        0x100e84cf5 - std::panicking::default_hook::hc1d0cb86aebc9fbd
   5:        0x100e85658 - std::panicking::rust_panic_with_hook::hbe9b3056eff949a6
   6:        0x100e851f2 - rust_begin_unwind
   7:        0x100e8516b - std::panicking::begin_panic_fmt::hb770b3908b606330
   8:        0x100e7dcd4 - std::io::stdio::_print::ha0a93283413e42a0
   9:        0x100d6caff - navi::handler::handle_config::h67eddfb5fb0f4075
  10:        0x100d365d3 - navi::main::h8037e7d6de60681c
  11:        0x100d3666b - std::rt::lang_start::{{closure}}::h0267afadc1f01a45
  12:        0x100e850b8 - std::panicking::try::do_call::h69374c200cb9b71d
  13:        0x100e9347b - __rust_maybe_catch_panic
  14:        0x100e814f3 - std::rt::lang_start_internal::h892855ab5abc97d0
  15:        0x100d36659 - main
```

**Comment by denisidoro** [comment]
What's the output of `navi widget bash`? Does it fail with the same error messages?

**Comment by hernanmd** [comment]
```bash
$ navi widget bash
#!/usr/bin/env bash

__call_navi() {
    local -r result="$(navi --print)"
    local -r linecount="$(echo "$result" | wc -l)"

    if [[ "$linecount" -lt 2 ]]; then
        printf "$result"
        return 0
    fi

    IFS=$'\n'
    local i=1;
    for line in $result; do
        if echo "$line" | grep -q '\\$'; then
            printf "${line::-1} "
        elif [[ "$i" -eq "$linecount" ]]; then
            printf "$line "
        else
            printf "${line}; "
        fi
        i=$((i+1))
    done
}

bind '"\C-g": " \C-b\C-k \C-u`__call_navi`\e\C-e\C-a\C-y\C-h\C-e\e \C-y\ey\C-x\C-x\C-f"'
```

**Comment by denisidoro** [comment]
Do you have zsh or fish? I'd like to validate if this is only happening with bash.

Could you start a zsh shell, for example, and run `source <(navi widget zsh)`?

**Comment by hernanmd** [comment]
Couldn't reproduce the problem with zsh (I don't have fish)

```bash
$ zsh
$ zsh --version
zsh 5.3 (x86_64-apple-darwin17.0)
${debian_chroot:+($debian_chroot)}\u@\h \w \$ source <(navi widget zsh)
```

**Comment by denisidoro** [comment]
Unfortunately I'm not able to reproduce the problem with my setup:
```bash
$ $0 --version
GNU bash, version 5.0.16(1)-release (x86_64-apple-darwin19.3.0)
```

I'll try to investigate it but any external help will be appreciated.

**Comment by denisidoro** [comment]
In the meantime, you can add the contents from `navi widget bash` directly into your `.bashrc`

**Comment by hernanmd** [comment]
Thank you @denisidoro I did it, works good with your suggestion :)

**Comment by denisidoro** [comment]
Fixed: https://github.com/denisidoro/navi/commit/22c0d0358693c7e579b49eb2a067cc970f3207b8
