### ISSUE TITLE
thread 'main' panicked on specific cheatsheet

### ISSUE THREAD

**Issue by pushou** [denisidoro/navi#917]
**Describe the bug**
One of my cheatsheet produce error
```
export RUST_BACKTRACE=1; navi
thread 'main' panicked at 'byte index 2 is not a char boundary; it is inside '\u{a0}' (bytes 1..3) of `# do not fragment off`', src/parser.rs:110:22
                 stack backtrace:
```

**To Reproduce**

1. Create a cheatsheet with

```
% bgp,cisco,pushou

# other
route-map nodf permit 10
set ip df 0
interface FastEthernet2
ip policy route-map nodf
```
3. Launch navi

4. Use UP arrow key 

6. See error trace
```
export RUST_BACKTRACE=1; navi
thread 'main' panicked at 'byte index 2 is not a char boundary; it is inside '\u{a0}' (bytes 1..3) of `# do not fragment off`', src/parser.rs:110:22
                 stack backtrace:
                               OAOOOOOOOOOO*
``
Remove lines in the cheatsheet and Navi worked as expected

**Expected behavior**
run Navi without error

**Versions:**

- OS: Ubuntu 24
- Navi 2.0.23
- zsh 5.9 (x86_64-ubuntu-linux-gnu) same behavior under bash

thanks for Navi !

**Comment by alexis-opolka** [comment]
IH @pushou,

Have you tried to update navi to the latest version, currently 2.0.24, to see if your issue still exists ?
As of now, I can't reproduce your issue.

The rust backtrace goes to `src/parser.rs:110:22` which is :

```rust
fn without_prefix(line: &str) -> String {
    if line.len() > 2 {
        String::from(line[2..].trim())
    } else {
        String::from("")
    }
}
```

and is called when parsing cheatsheets.
